### ISSUE TITLE
CNN generator: CNN_LargeConvolutionPoolReLU_Hor drop buffer tail with some input resulutions

### ISSUE THREAD

**Issue by asmorkalov** [GreenWaves-Technologies/autotiler#2]
In lines https://github.com/GreenWaves-Technologies/autotiler/blob/master/generators/CNN/generator/src/CNN_Generators.c#L789 and https://github.com/GreenWaves-Technologies/autotiler/blob/master/generators/CNN/generator/src/CNN_Generators.c#L790
`DROP_REM` constains should be replaced with `OBJ_CONSTRAINTS_DYNAMIC`.

**Comment by Yaooooo** [comment]
Thank you for your report, we will do a check and fix it asap.

**Comment by Pafrak** [comment]
On this point the OBJ_CONSTRAINTS_DYNAMIC is not a solution, it is just a workaround for some cases. Will look for a clean solution

**Comment by Pafrak** [comment]
This has been fixed with autotiler V3
