### ISSUE TITLE
CNN Generator: CNN_LargeConvolutionPoolReLU_Hor and CNN_LargeConvolutionPoolReLU_Ver generate invalid call sequence for average pooling

### ISSUE THREAD

**Issue by asmorkalov** [GreenWaves-Technologies/autotiler#3]
According to functions code, they can produce chains like Convolution -> ReLU, Convolution -> ReLU->Pooling, but not Convolution -> Pooling without ReLU.

**Comment by Pafrak** [comment]
this has been corrected in new version (V3) of autotiler
